name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: your-github-username
          output: dist/snake.svg

      - name: Create output directory
        run: mkdir -p dist

      - name: Move snake animation to dist directory
        run: mv dist/snake.svg dist/snake.svg

      - name: Push Snake Animation to Repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Generate Snake Animation"
          files: dist/snake.svg
          destination: dist/snake.svg
